from pathlib import Path

for name in ('index.html','app-v4.html'):
    p=Path(name)
    s=p.read_text(encoding='utf-8')

    s=s.replace('const roleLabel=r=>({admin:"관리자",leader:"셀 리더",helper:"헬퍼",viewer:"조회 전용",pending:"승인 대기"}[r]||r||"-");',
                'const roleLabel=r=>({admin:"관리자",leader:"셀 리더",helper:"헬퍼",member:"셀원",viewer:"조회 전용",pending:"승인 대기"}[r]||r||"-");')

    old='''function renderUsers(){\n if(!isAdmin())return;\n $("userBody").innerHTML=users.map(u=>{const ro=["pending","admin","leader","helper","viewer"].map(r=>`<option value="${r}" ${u.role===r?"selected":""}>${roleLabel(r)}</option>`).join(""),co='<option value="">셀 미지정</option>'+cells.map(c=>`<option value="${esc(c.id)}" ${u.cellId===c.id?"selected":""}>${esc(c.name)}</option>`).join(""),owner=(u.email||"").toLowerCase()===OWNER;return `<tr><td>${esc(u.name||"-")}</td><td>${esc(u.email||"")}</td><td><select data-role="${u.id}" ${owner?"disabled":""}>${ro}</select></td><td><select data-cell="${u.id}" ${owner?"disabled":""}>${co}</select></td><td>${owner?"고정 관리자":`<button class="soft" data-save-user="${u.id}">저장</button>`}</td></tr>`}).join("");\n $("userBody").querySelectorAll("[data-save-user]").forEach(b=>b.onclick=async()=>{const id=b.dataset.saveUser,role=document.querySelector(`[data-role="${id}"]`).value,cellId=document.querySelector(`[data-cell="${id}"]`).value;if(["leader","helper","viewer"].includes(role)&&!cellId)return alert("담당 셀을 지정해주세요.");await updateDoc(doc(db,"users",id),{role,cellId:["admin","pending"].includes(role)?"":cellId,updatedAt:Date.now()});alert("사용자 권한이 저장되었습니다.")});\n}\n'''

    new='''async function syncUserToCell(user,newRole,newCellId){\n const name=(user?.name||"").trim();\n if(!name)return;\n const oldRole=user?.role||"pending",oldCellId=user?.cellId||"";\n const relevant=["leader","helper","member"];\n const touched=new Set([oldCellId,newCellId].filter(Boolean));\n for(const cellId of touched){\n  const c=cells.find(x=>x.id===cellId);if(!c)continue;\n  let leader=String(c.leader||""),helper=String(c.helper||""),members=memberNames(c);\n  if(cellId===oldCellId){\n   if(oldRole==="leader"&&leader===name)leader="";\n   if(oldRole==="helper"&&helper===name)helper="";\n   if(oldRole==="member")members=members.filter(x=>x!==name);\n  }\n  if(cellId===newCellId){\n   members=members.filter(x=>x!==name);\n   if(newRole==="leader")leader=name;\n   else if(newRole==="helper")helper=name;\n   else if(newRole==="member")members.push(name);\n  }\n  const dedup=[...new Set(members.filter(Boolean))];\n  await updateDoc(doc(db,"cells",cellId),{leader,helper,members:dedup,updatedAt:Date.now()});\n }\n}\n\nfunction renderUsers(){\n if(!isAdmin())return;\n $("userBody").innerHTML=users.map(u=>{const ro=["pending","admin","leader","helper","member","viewer"].map(r=>`<option value="${r}" ${u.role===r?"selected":""}>${roleLabel(r)}</option>`).join(""),co='<option value="">셀 미지정</option>'+cells.map(c=>`<option value="${esc(c.id)}" ${u.cellId===c.id?"selected":""}>${esc(c.name)}</option>`).join(""),owner=(u.email||"").toLowerCase()===OWNER;return `<tr><td>${esc(u.name||"-")}</td><td>${esc(u.email||"")}</td><td><select data-role="${u.id}" ${owner?"disabled":""}>${ro}</select></td><td><select data-cell="${u.id}" ${owner?"disabled":""}>${co}</select></td><td>${owner?"고정 관리자":`<button class="soft" data-save-user="${u.id}">저장</button>`}</td></tr>`}).join("");\n $("userBody").querySelectorAll("[data-save-user]").forEach(b=>b.onclick=async()=>{\n  const id=b.dataset.saveUser,user=users.find(x=>x.id===id),role=document.querySelector(`[data-role="${id}"]`).value,cellId=document.querySelector(`[data-cell="${id}"]`).value;\n  if(["leader","helper","member","viewer"].includes(role)&&!cellId)return alert("담당 셀을 지정해주세요.");\n  const finalCellId=["admin","pending"].includes(role)?"":cellId;\n  b.disabled=true;b.textContent="저장 중...";\n  try{\n   await syncUserToCell(user,role,finalCellId);\n   await updateDoc(doc(db,"users",id),{role,cellId:finalCellId,updatedAt:Date.now()});\n   alert("사용자 권한과 셀 명단이 함께 저장되었습니다.");\n  }catch(e){console.error(e);alert("저장 실패: "+(e.code||e.message||e))}\n  finally{b.disabled=false;b.textContent="저장"}\n });\n}\n'''
    if old not in s:
        raise SystemExit(f'Could not find renderUsers block in {name}')
    s=s.replace(old,new)
    p.write_text(s,encoding='utf-8')

rp=Path('firestore.rules')
r=rp.read_text(encoding='utf-8')
r=r.replace("myRole() in ['admin', 'leader', 'helper', 'viewer']", "myRole() in ['admin', 'leader', 'helper', 'member', 'viewer']")
rp.write_text(r,encoding='utf-8')
